[package]
name = "atrium-metrics"

edition.workspace = true
version.workspace = true

[dependencies]
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }

[lints]
workspace = true
