default_install_hook_types: [pre-push]
repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        language: system
        pass_filenames: false
        entry: cargo x lint
      - id: lockfile
        name: lockfile
        language: system
        pass_filenames: false
        entry: cargo update -w --locked
