name: Merge CI
on:
  push:
    branches: [ main ]

jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: typos-cli,taplo-cli
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Describe
        run: |
          cargo x --version
          cargo --version
          rustc --version
      - uses: pre-commit/action@v3.0.1
